---
- name: Install dependencies (Debian)
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Run CrowdSec official repository setup script (Debian)
  ansible.builtin.shell: curl -s https://install.crowdsec.net | sudo bash
  args:
    creates: /etc/apt/sources.list.d/crowdsec_crowdsec.list
  when: ansible_facts['os_family'] == 'Debian'

- name: Install CrowdSec security engine (Debian)
  ansible.builtin.apt:
    name: crowdsec
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
