---
- name: Ensure secure-network exists
  community.docker.docker_network:
    name: secure-network
    state: present

- name: Create mount directory for custom storage
  ansible.builtin.file:
    path: /mnt/storage
    state: directory
    mode: '0755'

- name: Mount and configure /dev/sdb drive
  ansible.posix.mount:
    path: /mnt/storage
    src: /dev/sdb
    fstype: ext4
    opts: defaults,noatime
    state: mounted

- name: Configure sysctl parameters for high load and database stability
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { key: 'vm.overcommit_memory', value: '1' }
    - { key: 'vm.max_map_count', value: '262144' }
    - { key: 'fs.file-max', value: '2097152' }

- name: Check if swap file exists
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file_check

- name: Create swap file if it does not exist
  block:
    - name: Allocate space for swapfile
      ansible.builtin.command: fallocate -l 4G /swapfile
      changed_when: true

    - name: Set correct permissions for swapfile
      ansible.builtin.file:
        path: /swapfile
        mode: '0600'

    - name: Make swapfile
      ansible.builtin.command: mkswap /swapfile
      changed_when: true

    - name: Enable swapfile
      ansible.builtin.command: swapon /swapfile
      changed_when: true

    - name: Add swapfile to fstab
      ansible.builtin.mount:
        path: none
        src: /swapfile
        fstype: swap
        opts: sw
        state: present
  when: not swap_file_check.stat.exists
